#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Regenerate .scc files from patch queues.
#
#   generate-scc.sh <scc> <patchdir> <name>   per-queue .scc from patches/
#   generate-scc.sh --aggregator              tegra-patches.scc from branches.yaml

set -euo pipefail

_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEGRA_KERNEL_CACHE="${TEGRA_KERNEL_CACHE:-$(cd "${_SCRIPT_DIR}/.." && pwd)}"
export PYTHONPATH="${_SCRIPT_DIR}/lib${PYTHONPATH:+:$PYTHONPATH}"

generate_queue_scc() {
    local scc="$1" patchdir="$2" name="$3"
    local features_root="${TEGRA_KERNEL_CACHE}/features/tegra"

    [[ -d "$patchdir" ]] || mkdir -p "$patchdir"
    patchdir="$(cd "$patchdir" && pwd)"
    local rel="${patchdir#${features_root}/}"

    local cfg="${features_root}/${name}.cfg"

    {
        echo "# SPDX-License-Identifier: MIT"
        echo "# Auto-generated by scripts/generate-scc.sh — do not edit patch list by hand."
        echo "define KFEATURE_DESCRIPTION \"Tegra ${name}\""
        echo
        shopt -s nullglob
        for p in "$patchdir"/*.patch; do
            echo "patch ${rel}/$(basename "$p")"
        done
        shopt -u nullglob
        echo
        if [[ -f "$cfg" ]]; then
            echo "kconf hardware ${name}.cfg"
            echo
        fi
    } >"$scc"
}

generate_aggregator_scc() {
    python3 - "$TEGRA_KERNEL_CACHE" <<'PY'
import sys
from pathlib import Path

from manifest import export_order, load_manifest

cache_root = Path(sys.argv[1])
doc = load_manifest(cache_root / "sources" / "branches.yaml")
out = cache_root / doc.get("patches_scc", "features/tegra/tegra-patches.scc")
kconf = doc.get("patches_kconf", "cfg/tegra.cfg")
bbappend = f"linux-yocto_{doc['version_suffix']}.bbappend"

lines = [
    "# SPDX-License-Identifier: MIT",
    "# Auto-generated by scripts/generate-scc.sh --aggregator — do not edit by hand.",
    f"# Referenced from KERNEL_FEATURES:tegra in {bbappend}.",
    'define KFEATURE_DESCRIPTION "Tegra vendor patch queues"',
    "",
]
for q in export_order(doc):
    lines.append(f"include {q['scc']}")
lines += [
    "",
    f"kconf hardware {kconf}",
    "",
]
out.write_text("\n".join(lines), encoding="utf-8")
print(f"generate-scc: wrote {out}")
PY
}

case "${1:-}" in
    --aggregator)
        generate_aggregator_scc
        ;;
    -h|--help)
        echo "usage: $0 <scc> <patchdir> <name>" >&2
        echo "       $0 --aggregator" >&2
        exit 0
        ;;
    "")
        echo "usage: $0 <scc> <patchdir> <name> | $0 --aggregator" >&2
        exit 1
        ;;
    *)
        [[ $# -eq 3 ]] || {
            echo "usage: $0 <scc> <patchdir> <name> | $0 --aggregator" >&2
            exit 1
        }
        generate_queue_scc "$1" "$2" "$3"
        ;;
esac
